[package]
name = "postcard"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "pc-client"
path = "src/client.rs"


[[bin]]
name = "pc-server"
path = "src/server.rs"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1"
bytes = "1.0"
clap = { version = "3.0", features = ["derive"] }
futures = "0.3"
futures-util = "0.3"
hyper = { version="0.14", features = ["full"] }
h2 = "0.3"
hyper-rustls = { version="0.23", features = ["webpki-tokio", "http1", "http2", "tls12", "logging"] }
hyper-tls = "0.5"
nom = "7"
rustls = "0.20"
rustls-pemfile = "0.2"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["full"] }
tokio-rustls = "0.23"
tokio-native-tls ="0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
